modLoader="javafml"
loaderVersion="[${minFMLVersion},)"
issueTrackerURL="${modIssueUrl}"
license="${modLicense}"
logoFile="mod_logo.png"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
description="${modDescription}"
authors="${modAuthor}"
displayURL="${modPageUrl}"
updateJSONURL="${modUpdateUrl}"
displayTest="${modForgeDisplayTest}"

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="[${minForgeVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[${minMinecraftVersion},${nextMinecraftVersion})"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="fancymenu"
mandatory=false
versionRange="[2.14.7,)"
ordering="AFTER"
side="CLIENT"

[modproperties.${modId}]
catalogueImageIcon="mod_icon.png"
configuredBackground="minecraft:textures/block/gold_block.png"